version: '3.1'

services:

  database:
    image: mongo:4.2.16-bionic
    environment: 
      - MONGO_INITDB_DATABASE=${MONGODB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOTPASS}
    networks: 
      - database

  express:
    image: mongo-express:latest
    restart: always
    ports: 
      - 8081:8081
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGODB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGODB_ROOTPASS}
      - ME_CONFIG_MONGODB_URL=${MONGODB_URI}
    networks: 
      - database

  app:
    image: rizqipratama1st/todoapp:1
    restart: always
    ports: 
      - 3000:3000
      - 8080:8080
    environment: 
      - DB_URI=${MONGODB_URI}
      - DB_NAME=${MONGODB_NAME}
      - DB_COLLECTION_NAME=${MONGODB_COLLECTION}
    networks: 
      - database

networks:
  database:
    driver: bridge